In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
li = np.random.randint(0,100,size=(3,3,3))
print(li)

[[[13 31 81]
  [16 63  5]
  [97 16 55]]

 [[29 61 97]
  [97 64 11]
  [28 61 96]]

 [[24 17  9]
  [77 58 96]
  [58 65  9]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
li1 = np.diag(1+np.arange(4), k = -1)
print (li1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
li2 = np.zeros ((8,8), dtype=int)
li2[1::2, ::2]= 1
li2[::2, 1::2] = 1
print (li2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
li3 = np.random.random((5,5))
li3max, li3min = li3.max(), li3.min()
li3= (li3-li3min)/(li3max-li3min)
print (li3)

[[0.52268952 0.07377492 0.         0.394952   0.11494281]
 [0.70684317 0.55662269 0.50958171 0.19342811 0.03050295]
 [0.86396275 0.56905611 0.68175769 0.74744532 0.71305217]
 [0.98547003 0.64843856 0.25600904 0.1169744  1.        ]
 [0.23034546 0.48351858 0.10504063 0.34901236 0.67148498]]


# 5.  How to find common values between two arrays?

In [6]:
li4 = np.random.randint(0,10,10)

li5 = np.random.randint(0,10,10)

print(np.intersect1d(li4,li5))

[0 3 4 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("yesterday = ", yesterday )
print("today= ", today )
print("tomorrow = ", tomorrow )

yesterday =  2020-07-28
today=  2020-07-29
tomorrow =  2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [9]:
A = np.random.randint(0,2,5)

B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values

equal = np.allclose(A,B)

print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)

equal = np.array_equal(A,B)

print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [10]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.62393598 0.53663507 0.43530544 0.01474798 0.61009286 0.3768823
 0.79581451 0.         0.54472713 0.86777922]


# 9. How to print all the values of an array?

In [12]:
# np.set_printoptions(threshold=np.nan)

Z = np.zeros((16,16))

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [13]:
X = np.random.rand(5, 10)

# Recent versions of numpy

Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy

Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.06301124 -0.29978347  0.39840434 -0.16066145 -0.34699857  0.18945153
  -0.26869087  0.08925732  0.20759896  0.25443344]
 [-0.10531507 -0.30220604  0.3742691  -0.28067874 -0.13132275 -0.41790473
  -0.02044107 -0.10581538  0.43593194  0.55348274]
 [-0.02250276 -0.16182223 -0.10022042 -0.36632364  0.29961341 -0.30002299
   0.30185886 -0.1184011   0.3551645   0.11265637]
 [-0.2729983   0.10369762  0.23620021  0.43536676  0.12923623 -0.36501196
  -0.19722628  0.15508845 -0.1185355  -0.10581723]
 [-0.15411431 -0.05944188 -0.30282118 -0.07286537  0.21852896  0.46801656
   0.01992749  0.26842962 -0.4490137   0.0633538 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [14]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

# Another solution

# Author: Bartosz Telenczuk

np.add.at(Z, I, 1)

print(Z)

[5. 3. 2. 3. 4. 2. 3. 4. 3. 1.]
[9. 5. 3. 5. 7. 3. 5. 7. 5. 1.]


# 12.How to get the diagonal of a dot product?

In [15]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

# Slow version

np.diag(np.dot(A, B))

# Fast version

np.sum(A * B.T, axis=1)

# Faster version

np.einsum("ij,ji->i", A, B)

array([1.53501507, 1.70700977, 1.21726744, 1.1433571 , 0.88724404])

# 13.How to find the most frequent value in an array?

In [16]:
Z = np.random.randint(0,10,50)

print(np.bincount(Z).argmax())

0


# 14.How to get the n largest values of an array

In [17]:
Z = np.arange(10000)

np.random.shuffle(Z)

n = 5

# Slow

print (Z[np.argsort(Z)[-n:]])

# Fast

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


# 15.How to create a record array from a regular array?

In [18]:
Z = np.array([("Hello", 2.5, 3),

("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T,

names='col1, col2, col3',

formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
